# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

osx_image: xcode8.1
        
install:
- export DEPENDENCIES_DIRECTORY="${TRAVIS_BUILD_DIR}/dependencies"
- mkdir ${DEPENDENCIES_DIRECTORY} && cd ${DEPENDENCIES_DIRECTORY}
- if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.2/cmake-3.2.0-Linux-x86_64.tar.gz"
        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPENDENCIES_DIRECTORY}/cmake/bin:${PATH}
    fi
- |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew update
        brew install cmake
    fi
- |
    if [[ "$RUN_COVERAGE_TEST" == "1" ]]; then
        mkdir -p "${DEPENDENCIES_DIRECTORY}/gcov/bin"
        export PATH=${DEPENDENCIES_DIRECTORY}/gcov/bin:${PATH}
        ln -fs /usr/bin/gcov-4.9 "${DEPENDENCIES_DIRECTORY}/gcov/bin/gcov" && gcov --version
        pip install --user requests[security]
        pip install --user cpp-coveralls
    fi
- cd ${TRAVIS_BUILD_DIR}
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v

addons:
    apt:
        # List of whitelisted in travis packages for ubuntu-precise can be found here:
        #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
        # List of whitelisted in travis apt-sources:
        #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
        packages:
            - gcc-4.9
            - g++-4.9
            - clang-3.7
            - time
            - valgrind
    
os:
    - linux
    - osx

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - chmod +x travis.sh

script: ./travis.sh

after_success:
    - |
        if [[ "$RUN_COVERAGE_TEST" == "1" ]]; then
            cd ${TRAVIS_BUILD_DIR}
            coveralls --exclude "/usr" --exclude "test" --exclude "build/htd/CMakeFiles" --exclude "dependencies" --gcov-options '\-lbp'
        fi

after_failure:
    - |
        if [ -f "${TRAVIS_BUILD_DIR}/build/${HTD_TARGET}/Testing/Temporary/LastTest.log" ]; then
            cat "${TRAVIS_BUILD_DIR}/build/${HTD_TARGET}/Testing/Temporary/LastTest.log"
        fi

env:
    - HTD_TARGET=htd BUILD_SHARED_LIBS=True CMAKE_BUILD_TYPE=Debug HTD_USE_EXTENDED_IDENTIFIERS=True
    - HTD_TARGET=htd BUILD_SHARED_LIBS=True CMAKE_BUILD_TYPE=Debug HTD_USE_EXTENDED_IDENTIFIERS=False
    - HTD_TARGET=htd BUILD_SHARED_LIBS=False CMAKE_BUILD_TYPE=Debug HTD_USE_EXTENDED_IDENTIFIERS=True
    - HTD_TARGET=htd BUILD_SHARED_LIBS=False CMAKE_BUILD_TYPE=Debug HTD_USE_EXTENDED_IDENTIFIERS=False

matrix:
    include:
        - os: linux
          compiler: gcc
          env: HTD_TARGET=htd BUILD_SHARED_LIBS=True CMAKE_BUILD_TYPE=Debug HTD_USE_EXTENDED_IDENTIFIERS=False RUN_COVERAGE_TEST=1

notifications:
    email: false

sudo: false
